// This file was autogenerated by depswriter.py.
// Please do not edit.
goog.addDependency('../../../../src/parallel/parallel-exception.js', ['parallel.ParallelException'], [], false);
goog.addDependency('../../../../src/parallel/parallel.js', ['parallel'], ['parallel.SharedObject', 'parallel.ThreadPool', 'parallel.ThreadProxy'], false);
goog.addDependency('../../../../src/parallel/shared-object.js', ['parallel.SharedObject'], [], false);
goog.addDependency('../../../../src/parallel/thread-message.js', ['parallel.ThreadMessage'], [], false);
goog.addDependency('../../../../src/parallel/thread-pool.js', ['parallel.ThreadPool'], ['parallel.ParallelException', 'parallel.SharedObject', 'parallel.ThreadProxy'], false);
goog.addDependency('../../../../src/parallel/thread-proxy.js', ['parallel.ThreadProxy'], ['parallel.SharedObject', 'parallel.ThreadMessage'], false);
